USE localidades;

CREATE TABLE IF NOT EXISTS PREFEITO (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR (50) NOT NULL ,
DataPosse DATE NOT NULL  
);

ALTER TABLE CIDADE
ADD Prefeito_ID INT REFERENCES PREFEITO(ID);

ALTER TABLE CIDADE
DROP COLUMN Prefeito_ID;


INSERT INTO PREFEITO (Nome, DataPosse) VALUES
('João Paulo','2024-04-10'),
('Marcio Gomes','2024-04-11'),
('Jose Silva','2024-04-12'),
('Geovane Aparecido','2024-04-14');

INSERT INTO PREFEITO (Nome, DataPosse) VALUES
('Marlindo','2024-04-15'),
('Elvis','2024-04-16'),
('Patricio','2024-04-17'),
('Hector','2024-04-18'),
('Maicon','2024-04-19'),
('Flavio','2024-04-20');

SELECT * FROM CIDADE;
SELECT * FROM PREFEITO;
SELECT * FROM ESTADO;

UPDATE CIDADE
SET Prefeito_ID = 4
WHERE Id = 3;

SELECT PREFEITO.Nome , CIDADE.Nome, Estado.Sigla
FROM CIDADE
INNER JOIN PREFEITO ON CIDADE.Prefeito_ID = PREFEITO.Id
INNER JOIN ESTADO ON CIDADE.estado_id = Estado.Id ;

